services:
  app:
    build: .
    container_name: volshebny_app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - minio
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - ADMIN_URL=${ADMIN_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - GPT_API=${GPT_API}
      - HIGGSFIELD_API=${HIGGSFIELD_API}
      - KLING_API=${KLING_API}
      - NANO_API_KEY=${NANO_API_KEY}
      - FLUX_API_KEY=${FLUX_API_KEY}
      - TTAPI_KEY=${TTAPI_KEY}
      - USE_S3=${USE_S3}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - S3_ENDPOINT=minio
      - S3_PORT=9000
      - S3_USE_SSL=false
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./public:/usr/src/app/public
    networks:
      - volshebny-network

  db:
    image: postgres:14-alpine
    container_name: volshebny_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - volshebny-network

  redis:
    image: redis:6.2-alpine
    container_name: volshebny_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - volshebny-network

  # MinIO (S3 Compatible Storage)
  minio:
    image: minio/minio:latest
    container_name: volshebny_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - volshebny-network

  # Job to create bucket automatically
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY}); do
        echo '...waiting for minio...';
        sleep 5;
      done;
      /usr/bin/mc mb --ignore-existing myminio/${S3_BUCKET_NAME};
      /usr/bin/mc policy set download myminio/${S3_BUCKET_NAME};
      exit 0;
      "
    networks:
      - volshebny-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  volshebny-network:
    driver: bridge
